import assert from "node:assert/strict";
import fs from "node:fs/promises";
import path from "node:path";
import { createRequire } from "node:module";
import { fileURLToPath, pathToFileURL } from "node:url";

const require = createRequire(import.meta.url);
const directory = path.dirname(fileURLToPath(import.meta.url));
const manifest = JSON.parse(await fs.readFile(path.join(directory, "package.json"), "utf8"));
const roots = process.argv.slice(2);
const paths = roots.length ? roots.map(root => path.resolve(root)) : [directory];
const yamlManifestPath = require.resolve("yaml/package.json", { paths });
const bundlerPath = require.resolve("rolldown", { paths });
const formatterPath = require.resolve("prettier", { paths });
const yamlRoot = path.dirname(yamlManifestPath);
const yamlManifest = JSON.parse(await fs.readFile(yamlManifestPath, "utf8"));
const bundlerManifest = JSON.parse(await fs.readFile(require.resolve("rolldown/package.json", { paths }), "utf8"));
const formatterManifest = JSON.parse(await fs.readFile(require.resolve("prettier/package.json", { paths }), "utf8"));
for (const installed of [yamlManifest, bundlerManifest, formatterManifest]) assert.equal(installed.version, manifest.devDependencies[installed.name], `expected the pinned ${installed.name} version`);
assert.equal(yamlManifest.license, "ISC");
const license = await fs.readFile(path.join(yamlRoot, "LICENSE"), "utf8");
const { build } = await import(pathToFileURL(bundlerPath).href);
const { format } = require(formatterPath);
const result = await build({
  input: path.join(directory, "entry.mjs"),
  platform: "node",
  plugins: [
    {
      name: "pinned-queue-yaml",
      resolveId(source) {
        if (source === "yaml") return path.join(yamlRoot, "browser", "index.js");
        return null;
      },
    },
  ],
  output: {
    format: "cjs",
    sourcemap: false,
    banner: `// @ts-nocheck\n// Generated by scripts/work_queue_yaml/build.mjs from yaml@${yamlManifest.version}.\n// This self-contained module is copied with queue scripts; no runtime npm packages.\n/*\n${license}*/`,
  },
});
assert.equal(result.output.length, 1, "parser must be one self-contained CommonJS module");
const output = result.output[0];
assert.equal(output.type, "chunk");
assert.equal(output.imports.length, 0, "parser cannot require runtime packages");
const config = JSON.parse(await fs.readFile(path.resolve(directory, "../../.prettierrc.json"), "utf8"));
const portable = output.code.replace(/^\/\/#(?:end)?region[^\n]*\n/gm, "");
const code = await format(portable, { ...config, parser: "babel" });
await fs.writeFile(path.resolve(directory, "../../work_queue_yaml.cjs"), code);
