"use strict";

const assert = require("node:assert/strict");
const { fixture, mock, protocolFixture } = require("./work_queue_issues_checks.cjs");
const { main, journalPath, summaryBody } = require("./work_queue_issues.cjs");
const { readCheckedQueue, writeCheckedFiles } = require("./work_queue_checked_transport.cjs");
const { MAX_PROJECTION_TARGETS, preflightIssues, mutateIssues, issueReadQuery } = require("./work_queue_issue_api.cjs");
const q = require("./work_queue_replay.cjs");
const helpers = require("./work_queue_test_helpers.cjs");
const { canonical } = require("./work_queue_codec.cjs");
const { newWork } = require("./work_queue_graph.cjs");
const { publishWorkQueueRequest } = require("./work_queue_store.cjs");
const { main: snapshot } = require("./write_work_queue_snapshot.cjs");
const fs = require("node:fs");
const os = require("node:os");
const path = require("node:path");

function nativeOptions(m, f) {
  return {
    ...m.options,
    trustedContext: undefined,
    readCheckedQueue: undefined,
    writeCheckedFiles: undefined,
    context: { ...m.options.context, runId: f.origin.run_id, runAttempt: f.origin.run_attempt, sha: f.origin.ref, eventName: "workflow_dispatch" },
    workflowRef: `owner/repo/${f.origin.workflow}@refs/heads/main`,
  };
}

function registerTests({ describe, it, beforeEach, afterEach }) {
  let prompts;
  beforeEach(() => {
    prompts = process.env.GH_AW_PROMPTS_DIR;
    process.env.GH_AW_PROMPTS_DIR = path.resolve(__dirname, "../md");
  });
  afterEach(() => {
    if (prompts === undefined) delete process.env.GH_AW_PROMPTS_DIR;
    else process.env.GH_AW_PROMPTS_DIR = prompts;
  });
  describe("Issue projection transport and recovery acceptance", () => {
    it("rejects unpublishable target scope before creating an Issue or label", async () => {
      const f = fixture({ backing: false });
      f.log[0].operations[0].policy.pools.default.allowed_repositories = ["owner/other"];
      f.log[0].request = q.newRequest(f.log[0].request.id, "policy", f.log[0].actor, { operations: f.log[0].operations });
      const m = mock(f, { labelMissing: true });
      const result = await main(m.options);
      assert.ok(result.pending);
      assert.match(result.pending[0].reason, /not allowlisted/);
      assert.equal(m.issues.size, 0);
      assert.ok(!m.calls.some(call => call[0] === "mutation" || call[0] === "lock"));
    });

    it("rejects an Issue preflight with an inaccessible repository as a typed pending target", async () => {
      const f = fixture({ backing: true });
      const target = f.nodes[0];
      const resource = target.backing_issue;
      if (!resource) throw new Error("fixture is missing its backing Issue");
      await assert.rejects(
        preflightIssues({}, [{ work_id: target.work_id, resource }], {
          response: {
            i0: {
              issue: {
                databaseId: resource.resource_id,
                number: resource.number,
                repository: null,
              },
            },
          },
        }),
        { code: "projection_target_unavailable" }
      );
    });

    it("renders delightful packaged templates with generated-by footers on every body and Claim comment", async () => {
      const f = fixture({ worker: true, backing: false });
      const m = mock(f);
      assert.deepEqual((await main(m.options)).pending, []);
      assert.match(m.issues.get("1").body, /A new home for this Work/);
      assert.match(m.issues.get("1").body, /Follow the live summary/);
      assert.match(m.issues.get("1").body, /Generated by \[worker\]/);
      assert.match(m.issues.get("1").body, /blob\/work-queue\/work-queue\.jsonl/);
      assert.equal(m.comments.size, 2);
      for (const comment of m.comments.values()) {
        assert.match(comment.body, /Generated by \[worker\]/);
        assert.doesNotMatch(comment.body, /\{(?:generated_footer|work_id|claim_id|status_section)\}/);
      }
      assert.ok([...m.comments.values()].some(comment => /Runs and Claims/.test(comment.body)));
      assert.ok([...m.comments.values()].some(comment => /One attempt, one trail of evidence/.test(comment.body)));
    });

    it("keeps mandatory generated-by attribution even with a custom footer", async () => {
      const messages = process.env.GH_AW_SAFE_OUTPUT_MESSAGES;
      process.env.GH_AW_SAFE_OUTPUT_MESSAGES = JSON.stringify({ footer: "A custom team note." });
      try {
        const f = fixture({ backing: false });
        const m = mock(f);
        assert.deepEqual((await main(m.options)).pending, []);
        assert.match(m.issues.get("1").body, /Generated by \[dispatcher\]/);
        assert.ok([...m.comments.values()].every(comment => /Generated by \[dispatcher\]/.test(comment.body)));
      } finally {
        if (messages === undefined) delete process.env.GH_AW_SAFE_OUTPUT_MESSAGES;
        else process.env.GH_AW_SAFE_OUTPUT_MESSAGES = messages;
      }
    });

    it("fails explicitly for missing packaged templates without blind native writes", async () => {
      process.env.GH_AW_PROMPTS_DIR = path.join(__dirname, "missing-work-queue-templates");
      const m = mock(fixture({ backing: false }));
      const result = await main(m.options);
      assert.ok(result.pending);
      assert.match(result.pending[0].reason, /Failed to read file/);
      assert.equal(m.issues.size, 0);
      assert.equal(m.calls.filter(call => call[0] === "mutation").length, 0);
    });
    it("authenticates staged activation without binding Claims or writing Issues", async () => {
      const f = fixture({ worker: true });
      f.log.pop();
      const m = mock(f);
      const directory = fs.mkdtempSync(path.join(os.tmpdir(), "gh-aw-issue-staged-"));
      const env = { issues: process.env.GH_AW_WORK_QUEUE_ISSUES, transport: process.env.GH_AW_WORK_QUEUE_CHECKED_TRANSPORT };
      process.env.GH_AW_WORK_QUEUE_ISSUES = "true";
      process.env.GH_AW_WORK_QUEUE_CHECKED_TRANSPORT = "graphql";
      try {
        const result = await snapshot({ ...nativeOptions(m, f), staged: true, snapshotPath: path.join(directory, "snapshot.json") });
        assert.equal(result.worker.dispatch_id, f.assignment.dispatch_id);
        assert.equal(m.calls.filter(call => call[0] === "mutation" || call[0] === "lock").length, 0);
        assert.equal(m.state().dispatches.get(f.assignment.dispatch_id).run, undefined);
      } finally {
        if (env.issues === undefined) delete process.env.GH_AW_WORK_QUEUE_ISSUES;
        else process.env.GH_AW_WORK_QUEUE_ISSUES = env.issues;
        if (env.transport === undefined) delete process.env.GH_AW_WORK_QUEUE_CHECKED_TRANSPORT;
        else process.env.GH_AW_WORK_QUEUE_CHECKED_TRANSPORT = env.transport;
        fs.rmSync(directory, { recursive: true });
      }
    });

    it("closes existing or projector-created Issues only for a checked non-PR Result and trusted admission policy", async () => {
      const cases = ["keep-open", "close-on-result"].flatMap(policy => [false, true].flatMap(pr => [false, true].map(backing => ({ policy, pr, backing }))));
      for (const { policy, pr, backing } of cases) {
        const f = fixture({ worker: true, backing, payload: { task: "a", issue_completion_policy: policy === "keep-open" ? "close-on-result" : "keep-open" } });
        for (const rule of f.log[0].operations[0].policy.projectors) rule.completion_policy = policy;
        f.log[0].request = q.newRequest(f.log[0].request.id, "policy", f.log[0].actor, { operations: f.log[0].operations });
        f.log.push(helpers.finish(f.log, f.assignment.dispatch_id, "h1", "completed"));
        const state = q.replayTransactions(f.log);
        const dispatch = state.dispatches.get(f.assignment.dispatch_id);
        const claim = f.assignment.claims[0];
        f.log.push(
          helpers.operationCommit(
            f.log,
            "verified-result",
            "result",
            [
              {
                kind: "Result",
                work_id: claim.work_id,
                claim_id: claim.claim_id,
                completion_id: state.works.get(claim.work_id).completion_id,
                descriptor: pr ? { outputs: [{ type: "create_pull_request", resource: { repository: "owner/repo", kind: "pull_request", number: "9" } }] } : { value: "verified" },
                evidence: helpers.evidence(state, dispatch, "delivery", 50, { source: "verified_receipts", run_id: dispatch.run.run_id, run_attempt: 1, receipt: "unit_verified_receipt" }),
              },
            ],
            undefined,
            50
          )
        );
        if (policy === "keep-open" && !pr) {
          const settled = q.replayTransactions(f.log);
          const terminal = helpers.evidence(settled, dispatch, "terminal_run", 51, { run_id: dispatch.run.run_id, run_attempt: 1, status: "completed", conclusion: "success" });
          f.log.push(helpers.operationCommit(f.log, "release-completed", "release", [{ kind: "Release", dispatch_id: dispatch.dispatch_id, evidence: terminal }], helpers.reconciler, 51));
          const expanded = structuredClone(settled.policy);
          for (const rule of expanded.projectors) rule.completion_policy = "close-on-result";
          const operations = [{ kind: "Policy", epoch: "later", policy: expanded }];
          f.log.push(helpers.commit(q.replayTransactions(f.log).tip, "later-close-policy", "policy", helpers.administrator, { operations }, operations, 52, "later"));
        }
        const m = mock(f);
        assert.deepEqual((await main(m.options)).pending, []);
        assert.equal(m.issues.get("1").state, policy === "close-on-result" && !pr ? "CLOSED" : "OPEN");
        const summary = m.comments.get(m.state().works.get(claim.work_id).issue_summary);
        assert.match(summary.body, pr ? /Needs review/ : /Done/);
        if (pr) assert.match(summary.body, /owner\/repo\/pull\/9/);
      }
    });

    it("rejects an agent-selected human Issue before admission or any privileged Issue mutation", async () => {
      const f = fixture({ backing: false, payload: { task: "unrelated", issue_completion_policy: "close-on-result" } });
      f.nodes[0].backing_issue = fixture().nodes[0].backing_issue;
      f.log[1] = helpers.commit("genesis", "admitted", "submit", helpers.dispatcher, { nodes: f.nodes }, f.nodes, 1);
      assert.throws(() => q.replayTransactions(f.log), /installed projector exact-target grant/);
      const m = mock(f, { labelMissing: true });
      const issue = m.issues.get("1");
      issue.title = "Unrelated human Issue";
      issue.body = "Human-owned discussion";
      issue.labels.nodes = [];
      const result = await main(m.options);
      assert.ok(result.pending);
      assert.match(result.pending[0].reason, /exact-target grant/);
      assert.equal(issue.state, "OPEN");
      assert.equal(issue.title, "Unrelated human Issue");
      assert.equal(issue.body, "Human-owned discussion");
      assert.deepEqual(issue.labels.nodes, []);
      assert.equal(m.comments.size, 0);
      assert.ok(!m.calls.some(call => call[0] === "mutation" || call[0] === "lock"));
    });

    it("does not inherit another projector's exact-target grant", async () => {
      const f = fixture({ payload: { task: "a", issue_completion_policy: "close-on-result" } });
      delete f.log[0].operations[0].policy.projectors[0].backing_issues;
      f.log[0].request = q.newRequest(f.log[0].request.id, "policy", f.log[0].actor, { operations: f.log[0].operations });
      const m = mock(f, { labelMissing: true });
      assert.equal(m.state().works.size, 1);
      const result = await main(m.options);
      assert.ok(result.pending);
      assert.match(result.pending[0].reason, /installed projector authority/);
      assert.equal(m.comments.size, 0);
      assert.ok(!m.calls.some(call => call[0] === "mutation" || call[0] === "lock"));
    });

    it("requires the worker projector's entire lossless backing Issue identity", async () => {
      for (const field of ["repository_id", "resource_id", "number"]) {
        const f = fixture({ worker: true });
        f.log[0].operations[0].policy.projectors[1].backing_issues[0] = { ...f.nodes[0].backing_issue, [field]: "9999" };
        f.log[0].request = q.newRequest(f.log[0].request.id, "policy", f.log[0].actor, { operations: f.log[0].operations });
        const m = mock(f, { labelMissing: true });
        assert.equal(m.state().works.size, 1);
        const result = await main(m.options);
        assert.ok(result.pending);
        assert.match(result.pending[0].reason, /installed projector authority/);
        assert.equal(m.comments.size, 0);
        assert.ok(!m.calls.some(call => call[0] === "mutation" || call[0] === "lock"));
      }
    });

    it("measures both authenticated hooks and ordinary checked queue publication", async () => {
      const f = fixture();
      const m = mock(f);
      const options = nativeOptions(m, f);
      const activation = await main(options);
      assert.deepEqual(activation.pending, []);
      assert.equal(activation.metrics.requests, 9);
      assert.equal(activation.metrics.reads, 4);
      assert.equal(activation.metrics.mutations, 5);
      const env = process.env.GH_AW_WORK_QUEUE_CHECKED_TRANSPORT;
      process.env.GH_AW_WORK_QUEUE_CHECKED_TRANSPORT = "graphql";
      const before = m.calls.length;
      try {
        const actor = helpers.dispatcher;
        const node = newWork({ task: "ordinary admission" }, "ordinary", "n", "default", m.state().policy, 100);
        await publishWorkQueueRequest({
          githubClient: m.options.githubClient,
          owner: "owner",
          repo: "repo",
          context: f.origin,
          request: q.newRequest("ordinary-admission", "submit", actor, { nodes: [node] }),
          now: () => 100,
          core: { info: () => {} },
        });
        assert.equal(m.calls.length - before, 2);
      } finally {
        if (env === undefined) delete process.env.GH_AW_WORK_QUEUE_CHECKED_TRANSPORT;
        else process.env.GH_AW_WORK_QUEUE_CHECKED_TRANSPORT = env;
      }
      const conclusion = await main({ ...options, jobResults: { safe_outputs: { result: "failure" } } });
      assert.deepEqual(conclusion.pending, []);
      assert.equal(m.issues.size, 2);
      assert.equal(m.comments.size, 2);
      assert.ok([...m.comments.values()].every(comment => /does not establish Work cancellation or Result/.test(comment.body)));
      assert.equal(activation.metrics.requests + 2 + conclusion.metrics.requests, m.calls.length);
    });

    it("combines immutable-head discovery, handles, and preflight for 25 owned targets", async () => {
      const f = fixture({ count: 25 });
      const m = mock(f, { field: true });
      const options = nativeOptions(m, f);
      assert.deepEqual((await main(options)).pending, []);
      const before = m.calls.length;
      const unchanged = await main(options);
      assert.deepEqual(unchanged.pending, []);
      assert.equal(unchanged.metrics.requests, 6);
      assert.equal(unchanged.metrics.reads, 4);
      assert.equal(unchanged.metrics.mutations, 2);
      assert.equal(m.calls.length - before, 6);
      assert.ok(
        m.calls
          .slice(before)
          .filter(call => call[0] === "mutation")
          .every(call => /WorkQueueProjection(?:Locks|Unlocks)/.test(call[1]))
      );
    });

    it("measures native creation, receipt journals, bindings, and new Issue coordination", async () => {
      const f = fixture({ backing: false });
      const m = mock(f, { field: true });
      const result = await main(nativeOptions(m, f));
      assert.deepEqual(result.pending, []);
      assert.equal(result.metrics.requests, 15);
      assert.equal(result.metrics.requests, m.calls.length);
      assert.equal(m.locks.size, 0);
    });

    it("projects two workflows sharing a queue and label without touching foreign backing Issues", async () => {
      const f = fixture({ count: 2 });
      f.log[0].operations[0].policy.projectors.push({ ...f.log[0].operations[0].policy.projectors[0], workflow: ".github/workflows/other.lock.yml" });
      f.log[0].request = q.newRequest(f.log[0].request.id, "policy", f.log[0].actor, { operations: f.log[0].operations });
      f.log[1] = helpers.commit("genesis", "mine", "submit", helpers.dispatcher, { nodes: [f.nodes[0]] }, [f.nodes[0]], 1);
      const other = { ...helpers.dispatcher, workflow: ".github/workflows/other.lock.yml", run_id: "999" };
      f.log.push(helpers.commit("mine", "theirs", "submit", other, { nodes: [f.nodes[1]] }, [f.nodes[1]], 2));
      const m = mock(f);
      assert.deepEqual((await main(m.options)).pending, []);
      assert.equal(m.comments.size, 1);
      assert.equal([...m.comments.values()][0].issue.id, "Issue1");
      assert.equal(m.state().works.get(f.nodes[1].work_id).issue_summary, undefined);
      const before = m.calls.length;
      assert.deepEqual((await main({ ...m.options, trustedContext: helpers.context(other, { ref: f.origin.ref }) })).pending, []);
      assert.equal(m.comments.size, 2);
      const writes = m.calls.slice(before).filter(call => call[0] === "mutation");
      assert.ok(
        writes.every(call =>
          Object.values(call[2])
            .filter(value => value?.subjectId)
            .every(value => value.subjectId === "Issue2")
        )
      );
    });

    it("reads new lifecycle state only after acquiring coordination, not the activation snapshot", async () => {
      const f = fixture();
      const m = mock(f);
      await main(m.options);
      const original = m.options.githubClient.rest.git.createRef;
      let advanced = false;
      m.options.githubClient.rest.git.createRef = async input => {
        const result = await original(input);
        if (!advanced) {
          advanced = true;
          const grant = helpers.grant(m.state().transactions);
          m.setLog([...m.state().transactions, grant.commit]);
        }
        return result;
      };
      assert.deepEqual((await main(m.options)).pending, []);
      assert.match([...m.comments.values()][0].body, /Status: \*\*Assigned\*\*/);
    });

    it("keeps proven successes and releases their locks when a sibling native create is ambiguous", async () => {
      const f = fixture({ count: 2, backing: false });
      const m = mock(f);
      const original = m.options.githubClient.graphql;
      let once = true;
      m.options.githubClient.graphql = async (query, variables) => {
        if (once && query.includes("WorkQueueIssueProjection")) {
          once = false;
          const result = await original(query, variables);
          throw Object.assign(new Error("partial unknown response"), { data: { m0: result.m0 }, errors: [{ type: "INTERNAL", path: ["m1"] }] });
        }
        return original(query, variables);
      };
      const options = nativeOptions(m, f);
      const result = await main(options);
      assert.ok(result.pending);
      assert.equal(result.pending.length, 1);
      assert.ok(m.state().works.get(f.nodes[0].work_id).issue_link);
      assert.equal(m.state().works.get(f.nodes[1].work_id).issue_link, undefined);
      assert.equal(m.locks.size, 1);
      await main(options);
      assert.equal(m.issues.size, 2);
      assert.ok(m.state().works.get(f.nodes[0].work_id).issue_summary);
    });

    it("uses withRetry for a proven pre-execution creation rejection without retrying ambiguous writes", async () => {
      const operation = { key: "work", name: "createIssue", type: "CreateIssueInput", input: {}, selection: "issue { id }" };
      let attempts = 0;
      const success = await mutateIssues(
        {
          graphql: async () => {
            if (++attempts === 1) throw Object.assign(new Error("rate limit exceeded"), { errors: [{ type: "RATE_LIMITED" }] });
            return { m0: { issue: { id: "new" } } };
          },
        },
        [operation]
      );
      assert.equal(attempts, 2);
      assert.equal(success.ambiguous, false);
      attempts = 0;
      const uncertain = await mutateIssues(
        {
          graphql: async () => {
            attempts++;
            throw Object.assign(new Error("timeout after native creation"), { status: 504 });
          },
        },
        [operation]
      );
      assert.equal(attempts, 1);
      assert.equal(uncertain.ambiguous, true);
    });

    for (const kind of ["Issue", "comment"]) {
      it(`cannot distinguish interrupted ${kind} creation from an accepted write with a lost receipt`, async () => {
        const receipts = [];
        for (const remoteAccepted of [false, true]) {
          const f = fixture({ backing: kind === "comment" });
          const m = mock(f);
          const send = m.options.githubClient.graphql;
          let sends = 0;
          m.options.githubClient.graphql = async (query, variables) => {
            if (query.includes("WorkQueueIssueProjection")) {
              sends++;
              if (remoteAccepted) await send(query, variables);
              throw new Error("interrupted before saving a native receipt");
            }
            return send(query, variables);
          };
          const options = nativeOptions(m, f);
          const first = await main(options);
          assert.ok(first.pending?.length);
          assert.equal(sends, 1);
          assert.equal(kind === "Issue" ? m.issues.size : m.comments.size, remoteAccepted ? 1 : 0);
          const journal = m.journals.get(journalPath(f.nodes[0].work_id));
          const receipt = kind === "Issue" ? journal.create : journal.comments.summary;
          assert.equal(receipt.resource, undefined);
          assert.equal(receipt.id, undefined);
          receipts.push({ ...receipt, nonce: "opaque-nonce" });
          assert.ok(m.locks.size > 0);
          const next = await main(options);
          assert.ok(next.pending?.some(item => /lock is held|acquisition is uncertain/.test(item.reason)));
          assert.equal(sends, 1);
          assert.equal(kind === "Issue" ? m.issues.size : m.comments.size, remoteAccepted ? 1 : 0);
        }
        assert.deepEqual(receipts[0], receipts[1]);
      });
    }

    it("does not let an authenticated rerun rewrite attempt-one execution status", async () => {
      const f = fixture({ worker: true });
      const m = mock(f, { field: true });
      const options = nativeOptions(m, f);
      assert.deepEqual((await main(options)).pending, []);
      assert.equal(m.issues.get("1").issueFieldValues.nodes[0].optionId, "option-Running");
      const before = m.calls.length;
      const comments = [...m.comments.values()].map(comment => comment.body);
      m.nativeRun.run_attempt = 2;
      const rerun = await main({ ...options, context: { ...options.context, runAttempt: 2 } });
      assert.ok(rerun.pending?.length);
      assert.match(rerun.pending[0].reason, /rerun_not_authorized|native attempt 1|original authenticated Claims/);
      assert.equal(m.calls.slice(before).filter(call => call[0] === "mutation").length, 0);
      assert.equal(m.issues.get("1").issueFieldValues.nodes[0].optionId, "option-Running");
      assert.deepEqual(
        [...m.comments.values()].map(comment => comment.body),
        comments
      );
    });

    it("chunks arbitrarily large operation lists into bounded native batches", async () => {
      const operations = Array.from({ length: 101 }, (_, key) => ({ key, name: "addComment", type: "AddCommentInput", input: {}, selection: "commentEdge { node { id } }" }));
      const sizes = [];
      const batch = await mutateIssues(
        {
          graphql: async (_query, variables) => {
            const aliases = Object.keys(variables).filter(key => /^m\d+$/.test(key));
            sizes.push(aliases.length);
            return Object.fromEntries(aliases.map(key => [key, { commentEdge: { node: { id: key } } }]));
          },
        },
        operations,
        { sleep: async () => {} }
      );
      assert.deepEqual(sizes, [50, 50, 1]);
      assert.equal(batch.results.length, 101);
      assert.equal(batch.ambiguous, false);
    });

    it("persists valid native receipts even when a sibling creation response is malformed", async () => {
      const f = fixture({ count: 2, backing: false });
      const m = mock(f);
      const send = m.options.githubClient.graphql;
      let once = true;
      m.options.githubClient.graphql = async (query, variables) => {
        const response = await send(query, variables);
        if (once && query.includes("WorkQueueIssueProjection")) {
          once = false;
          response.m0.issue = null;
        }
        return response;
      };
      const result = await main(m.options);
      assert.ok(result.pending);
      assert.equal(result.pending.length, 1);
      assert.equal(m.state().works.get(f.nodes[0].work_id).issue_link, undefined);
      assert.ok(m.state().works.get(f.nodes[1].work_id).issue_link);
      assert.ok(m.journals.get(journalPath(f.nodes[1].work_id)).create.resource);
      assert.equal(m.issues.size, 2);
    });

    it("keeps native creation receipts durable when concurrent admission wins the Issue binding", async () => {
      const f = fixture({ backing: false });
      const grantedIssue = fixture().nodes[0].backing_issue;
      for (const rule of f.log[0].operations[0].policy.projectors) rule.backing_issues = [grantedIssue];
      f.log[0].request = q.newRequest(f.log[0].request.id, "policy", f.log[0].actor, { operations: f.log[0].operations });
      const m = mock(f);
      const write = m.options.writeCheckedFiles;
      let once = true;
      m.options.writeCheckedFiles = async options => {
        if (once && options.files.some(file => file.path === "work-queue.jsonl")) {
          once = false;
          const native = m.issues.get("1");
          const other = newWork({ task: "concurrent human binding" }, "other", "n", "default", m.state().policy, 100);
          other.backing_issue = { kind: "issue", host: "github.com", repository: "owner/repo", repository_id: "1", resource_id: String(native.databaseId), number: "1" };
          const actor = { ...helpers.dispatcher, run_id: "999" };
          m.setLog([...m.state().transactions, helpers.commit(m.state().tip, "concurrent-admission", "submit", actor, { nodes: [other] }, [other], 100)]);
          throw Object.assign(new Error("expected head changed"), { status: 409 });
        }
        return write(options);
      };
      const result = await main(m.options);
      assert.ok(result.pending);
      assert.ok(result.pending.length);
      assert.equal(m.state().works.get(f.nodes[0].work_id).issue_link, undefined);
      assert.equal(m.journals.get(journalPath(f.nodes[0].work_id)).create.resource.number, "1");
      await main(m.options);
      assert.equal(m.issues.size, 1);
      assert.equal(m.comments.size, 0);
    });

    it("persists a sibling comment handle when one comment response is malformed", async () => {
      const f = fixture({ count: 2 });
      const m = mock(f);
      const send = m.options.githubClient.graphql;
      m.options.githubClient.graphql = async (query, variables) => {
        const response = await send(query, variables);
        if (query.includes("addComment")) response.m0.commentEdge.node.body = "not the requested body";
        return response;
      };
      const result = await main(m.options);
      assert.ok(result.pending);
      assert.equal(result.pending.length, 1);
      assert.equal(m.state().works.get(f.nodes[0].work_id).issue_summary, undefined);
      assert.ok(m.state().works.get(f.nodes[1].work_id).issue_summary);
      assert.ok(m.journals.get(journalPath(f.nodes[1].work_id)).comments.summary.id);
      assert.equal(m.locks.size, 2);
    });

    it("excludes an overlapping projector until the old checked-read/write phase finishes", async () => {
      const f = fixture();
      const m = mock(f, { field: true });
      const send = m.options.githubClient.graphql;
      let overlap;
      let once = true;
      m.options.githubClient.graphql = async (query, variables) => {
        if (once && query.includes("WorkQueueIssueProjection")) {
          once = false;
          const grant = helpers.grant(m.state().transactions);
          m.setLog([...m.state().transactions, grant.commit]);
          overlap = await main(nativeOptions(m, f));
        }
        return send(query, variables);
      };
      assert.deepEqual((await main(nativeOptions(m, f))).pending, []);
      assert.equal(overlap.pending.length, 1);
      assert.equal(m.comments.size, 1);
      assert.equal(m.locks.size, 0);
      assert.deepEqual((await main(nativeOptions(m, f))).pending, []);
      assert.equal(m.issues.get("1").issueFieldValues.nodes[0].optionId, "option-Assigned");
    });

    it("does not confuse unattempted aliases with uncertain native writes", async () => {
      const operations = Array.from({ length: 60 }, (_, key) => ({ key, name: "addComment", type: "AddCommentInput", input: {}, selection: "commentEdge { node { id } }" }));
      const batch = await mutateIssues(
        {
          graphql: async () => {
            throw new Error("lost first batch");
          },
        },
        operations,
        { sleep: async () => {} }
      );
      assert.equal(batch.results.length, 60);
      assert.ok(batch.results.slice(0, 50).every(result => result.uncertain));
      assert.ok(batch.results.slice(50).every(result => result.unattempted && !result.uncertain));
    });

    it("paginates scoped labels and field-value unions without overwriting unrelated values", async () => {
      const f = fixture();
      const m = mock(f, { field: true });
      const issue = m.issues.get("1");
      issue.labels.pageInfo = { hasNextPage: true, endCursor: "label-next" };
      issue.issueFieldValues.pageInfo = { hasNextPage: true, endCursor: "field-next" };
      const original = m.options.githubClient.graphql;
      m.options.githubClient.graphql = async (query, variables) => {
        if (query.includes("WorkQueueIssuePages"))
          return {
            p0: { id: issue.id, repository: { id: issue.repository.id }, labels: { nodes: [{ id: "human", name: "human" }], pageInfo: { hasNextPage: false } } },
            p1: { id: issue.id, repository: { id: issue.repository.id }, issueFieldValues: { nodes: [{ field: { id: "human-field" }, optionId: "human-option" }], pageInfo: { hasNextPage: false } } },
          };
        return original(query, variables);
      };
      const issues = await preflightIssues(m.options.githubClient, [{ work_id: f.nodes[0].work_id, resource: f.nodes[0].backing_issue }]);
      assert.equal(issues.get(f.nodes[0].work_id).labels.nodes.length, 2);
      assert.equal(issues.get(f.nodes[0].work_id).issueFieldValues.nodes[0].optionId, "human-option");
      assert.equal(m.calls.filter(call => call[1]?.includes("WorkQueueIssuePreflight")).length, 1);
    });

    it("reports changed field types, missing options, transferred/deleted Issues, and deleted handles as pending", async () => {
      for (const alteration of ["type", "options", "transfer", "delete", "comment"]) {
        const f = fixture();
        const m = mock(f, { field: true });
        await main(m.options);
        if (alteration === "type") m.discovery.issueFields.nodes[0].__typename = "IssueFieldText";
        if (alteration === "options") m.discovery.issueFields.nodes[0].options.pop();
        if (alteration === "transfer") m.issues.get("1").repository.nameWithOwner = "owner/foreign";
        if (alteration === "delete") m.issues.delete("1");
        if (alteration === "comment") m.comments.clear();
        const before = m.calls.length;
        const result = await main(m.options);
        assert.ok(result.pending);
        assert.ok(result.pending.length > 0, alteration);
        const writes = m.calls.slice(before).filter(call => call[0] === "mutation");
        if (alteration === "type" || alteration === "options") {
          assert.ok(
            writes.every(call => !/setIssueFieldValue|createIssueField/.test(call[1])),
            alteration
          );
          assert.ok([...m.comments.values()].some(comment => /field sync pending/.test(comment.body) && !/Status:/.test(comment.body)));
        } else assert.equal(writes.length, 0, alteration);
      }
    });

    it("creates only a missing tracking label, never provisions native fields", async () => {
      const m = mock(fixture(), { labelMissing: true });
      assert.deepEqual((await main(m.options)).pending, []);
      assert.ok(m.discovery.label);
      assert.equal(m.discovery.label.name, "work");
      const writes = m.calls
        .filter(call => call[0] === "mutation")
        .map(call => call[1])
        .join("\n");
      assert.match(writes, /createLabel/);
      assert.doesNotMatch(writes, /createIssueField|updateIssueField/);
    });

    it("stops all subsequent live calls when a rate limit is exhausted", async () => {
      const m = mock(fixture({ count: 26 }));
      m.options.githubClient.rest.git.createRef = async () => {
        m.calls.push(["rate-limit"]);
        throw Object.assign(new Error("rate limited"), { status: 429, response: { headers: { "retry-after": "60" } } });
      };
      const result = await main(m.options);
      assert.ok(result.pending);
      assert.equal(result.pending.length, 26);
      assert.equal(m.calls.filter(call => call[0] === "rate-limit").length, 1);
      assert.equal(m.calls.filter(call => call[0] === "mutation").length, 0);
    });

    it("recovers expected-head conflicts and lost publication acknowledgements without duplicate bindings", async () => {
      for (const mode of ["conflict", "acknowledgement"]) {
        const f = fixture({ backing: false });
        const m = mock(f);
        const original = m.options.writeCheckedFiles;
        let once = true;
        m.options.writeCheckedFiles = async input => {
          if (!once || !input.files.some(file => file.path === "work-queue.jsonl")) return original(input);
          once = false;
          if (mode === "acknowledgement") await original(input);
          throw Object.assign(new Error(mode), { status: mode === "conflict" ? 409 : 502 });
        };
        assert.deepEqual((await main(m.options)).pending, []);
        assert.equal(m.issues.size, 1);
        assert.equal(m.comments.size, 1);
      }
    });

    it("rejects forged native receipt identities and comment-handle reuse", async () => {
      const f = fixture({ backing: false });
      const m = mock(f);
      m.issues.set("1", mock(fixture()).issues.get("1"));
      m.journals.set(journalPath(f.nodes[0].work_id), {
        version: 1,
        work_id: f.nodes[0].work_id,
        comments: {},
        create: { nonce: "nonce", origin: { ...helpers.dispatcher, role: "projector" }, ref: f.origin.ref, resource: fixture().nodes[0].backing_issue, node_id: "foreign-node" },
      });
      const result = await main(m.options);
      assert.ok(result.pending);
      assert.match(result.pending[0].reason, /receipt node identity/);
      assert.equal(m.state().works.get(f.nodes[0].work_id).issue_link, undefined);
      const protocol = protocolFixture();
      const actor = { ...helpers.dispatcher, role: "projector" };
      const operation = { kind: "IssueComment", work_id: protocol.nodes[1].work_id, comment_id: "summary-0", projector_ref: f.origin.ref };
      assert.throws(() => q.replayTransactions([...protocol.log, helpers.operationCommit(protocol.log, "reuse", "issue_link", [operation], actor)]), /already belongs/);
    });

    it("rejects Claim comments colliding with another Work's summary, but accepts the original summary handle", () => {
      const f = fixture({ count: 2, worker: true });
      const actor = { ...helpers.workerActor(q.replayTransactions(f.log), f.assignment.dispatch_id), role: "projector" };
      const [first, second] = f.assignment.claims;
      const summary = { kind: "IssueComment", work_id: second.work_id, comment_id: "shared-summary", projector_ref: f.origin.ref, authority_claim_id: second.claim_id };
      f.log.push(helpers.operationCommit(f.log, "summary", "issue_link", [summary], actor));
      const same = helpers.operationCommit(f.log, "same-summary", "issue_link", [summary], actor);
      assert.equal(q.replayTransactions([...f.log, same]).works.get(second.work_id).issue_summary, "shared-summary");
      for (const claim of [first, second]) {
        const collision = { kind: "IssueComment", work_id: claim.work_id, claim_id: claim.claim_id, comment_id: "shared-summary", projector_ref: f.origin.ref };
        assert.throws(() => q.replayTransactions([...f.log, helpers.operationCommit(f.log, `collision-${claim.claim_id}`, "issue_link", [collision], actor)]), /Claim comment handle already belongs to a Work summary/);
      }
    });

    it("enforces the shared target cap while projecting all permitted targets in bounded batches", async () => {
      const f = fixture({ count: MAX_PROJECTION_TARGETS + 1 });
      assert.throws(
        () =>
          issueReadQuery(
            f.nodes.map(node => ({ work_id: node.work_id, resource: node.backing_issue })),
            { label: "work" },
            "owner/repo"
          ),
        /projection_limit/
      );
      const m = mock(f);
      assert.deepEqual((await main(m.options)).pending, []);
      assert.equal(m.comments.size, MAX_PROJECTION_TARGETS + 1);
    });

    it("rejects moved immutable aliases, nonregular ledger modes, unsafe publication paths, and oversized journals", async () => {
      const f = fixture();
      const m = mock(f);
      const original = m.options.githubClient.graphql;
      const client = {
        ...m.options.githubClient,
        graphql: async (query, variables) => {
          const response = await original(query, variables);
          response.repository.log.oid = "foreign";
          return response;
        },
      };
      await assert.rejects(() => readCheckedQueue({ githubClient: client, owner: "owner", repo: "repo" }), /immutable checked head/);
      await assert.rejects(
        () => writeCheckedFiles({ githubClient: m.options.githubClient, owner: "owner", repo: "repo", branch: "work-queue", expectedHeadOid: "a".repeat(40), files: [{ path: "../outside", content: "" }] }),
        /explicit head and files/
      );
      await assert.rejects(
        () => writeCheckedFiles({ githubClient: m.options.githubClient, owner: "owner", repo: "repo", branch: "work-queue", expectedHeadOid: "a".repeat(40), files: [{ path: journalPath("x"), content: "x".repeat(1024 * 1024 + 1) }] }),
        /explicit head and files/
      );
    });

    it("uses an immutable REST blob fallback only for explicitly truncated GraphQL text", async () => {
      const f = fixture();
      const m = mock(f);
      const original = m.options.githubClient.graphql;
      let text;
      let oid;
      m.options.githubClient.graphql = async (query, variables) => {
        const response = await original(query, variables);
        text = response.repository.log.text;
        oid = response.repository.log.oid;
        response.repository.log.text = null;
        response.repository.log.isTruncated = true;
        return response;
      };
      m.options.githubClient.rest.git.getBlob = async input => {
        assert.equal(input.file_sha, oid);
        return { data: { sha: oid, size: Buffer.byteLength(text), encoding: "base64", content: Buffer.from(text).toString("base64") } };
      };
      const checked = await readCheckedQueue({ githubClient: m.options.githubClient, owner: "owner", repo: "repo" });
      assert.equal(checked.state.works.size, 1);
      assert.equal(canonical(checked.transactions), canonical(f.log));
    });

    it("renders lossless verified output links without equating native job failure with Work cancellation", () => {
      const f = fixture();
      const state = q.replayTransactions(f.log);
      const work = state.works.get(f.nodes[0].work_id);
      work.result = { outputs: [{ resource: { repository: "owner/repo", kind: "pull_request", number: "9007199254740993" } }] };
      assert.match(summaryBody(state, work, undefined, 100), /pull\/9007199254740993/);
    });
  });
}

module.exports = { registerTests };
