// @ts-check
"use strict";

const { getPromptPath, renderTemplateFromFile } = require("./messages_core.cjs");
const { buildGeneratedFooter } = require("./markdown_body_helpers.cjs");

const PROGRESS_NOTES = {
  Queued: "Ready for its next fair slot.",
  Blocked: "Waiting for dependencies or a retry window.",
  Assigned: "An original Claim is reserved; its native run is not yet authenticated.",
  Running: "An authenticated run is carrying this Work forward.",
  Verifying: "The Claim has completed. Delivery is still being independently verified.",
  "Needs review": "Verified PR delivery is ready for human review. A PR is not a merge.",
  Done: "The recorded delivery has been independently verified.",
  "Needs attention": "Delivery needs attention; inspect the diagnostics below.",
  Cancelled: "Cancellation is recorded in Git. It does not terminate a native worker.",
};

function runLink(run) {
  return `https://github.com/${run.repository}/actions/runs/${run.run_id}/attempts/${run.run_attempt}`;
}

function renderWorkQueueMessage(template, values, run) {
  const workflowName =
    process.env.GH_AW_WORKFLOW_NAME ||
    run.workflow
      .split("/")
      .at(-1)
      .replace(/\.lock\.yml$/, "");
  const runUrl = runLink(run);
  let footer = buildGeneratedFooter({ workflowName, runUrl });
  if (!/^> Generated by /m.test(footer)) footer = `${renderTemplateFromFile(getPromptPath("work_queue_generated_footer.md"), { workflow_name: workflowName, run_url: runUrl }).trimEnd()}\n\n${footer}`;
  const message = renderTemplateFromFile(getPromptPath(template), { ...values, generated_footer: footer }).trimEnd();
  return message.endsWith(footer) ? message : `${message}\n\n${footer}`;
}

function issueBody(state, work, origin, config, branch) {
  const admission = state.transactions[work.position.commit].actor;
  const ledgerUrl = `https://github.com/${state.repository}/blob/${branch}/work-queue.jsonl`;
  return renderWorkQueueMessage(
    "work_queue_issue_body.md",
    {
      work_id: work.work_id,
      admission_run_url: admission.run_id ? runLink(admission) : ledgerUrl,
      admission_link_label: admission.run_id ? "View the admitting run" : "View the admission receipt",
      ledger_url: ledgerUrl,
      tracking_label: config.label,
      projection_note: config["status-field"] ? "Progress is projected into the configured native Issue status field when synchronization is available." : "The live summary carries its current status.",
    },
    origin
  );
}

function renderSummary(values, run, status, nativeField) {
  const statusSection = nativeField ? "" : renderTemplateFromFile(getPromptPath("work_queue_issue_status.md"), { status }).trimEnd();
  return renderWorkQueueMessage(
    "work_queue_issue_summary.md",
    {
      ...values,
      status_section: statusSection,
      progress_note: nativeField ? "Progress is tracked in the native Issue status field. The links below follow the checked ledger." : PROGRESS_NOTES[status],
    },
    run
  );
}

function renderClaim(values, run) {
  return renderWorkQueueMessage("work_queue_issue_claim.md", values, run);
}

module.exports = { issueBody, renderSummary, renderClaim, runLink };
